"use client";

import { Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import type { ArchiveChecklistItem } from "@/lib/archive/checklists";

interface ArchiveChecklistStepProps {
  checklist: ArchiveChecklistItem[];
  uploadedCount: number;
  totalCount: number;
  onUpload: (item: ArchiveChecklistItem) => void;
  uploading: boolean;
}

export function ArchiveChecklistStep({ checklist, uploadedCount, totalCount, onUpload, uploading }: ArchiveChecklistStepProps) {
  const progress = totalCount > 0 ? (uploadedCount / totalCount) * 100 : 0;

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2">
        <Progress value={progress} className="flex-1" />
        <span className="text-sm text-muted-foreground">{uploadedCount}/{totalCount}</span>
      </div>

      <div className="space-y-2">
        {checklist.map((item) => (
          <div key={item.id} className="flex items-center justify-between rounded border p-3">
            <div className="flex items-center gap-2">
              {item.required && <AlertTriangle className="h-4 w-4 text-amber-500" />}
              <span>{item.label}</span>
            </div>
            <Button size="sm" variant="outline" onClick={() => onUpload(item)} disabled={uploading}>
              <Upload className="mr-2 h-3.5 w-3.5" />
              {item.autoGenerated ? "系统生成" : "上传"}
            </Button>
          </div>
        ))}
      </div>
    </div>
  );
}

import { AlertTriangle } from "lucide-react";
