"use client";

import { useEffect, useRef, useState, useTransition, useCallback } from "react";
import { toast } from "sonner";
import { archiveMatter, getArchivePrepData } from "@/server/archive/actions";
import { uploadDocument } from "@/server/documents/actions";
import { type ArchiveChecklist, type ArchiveChecklistItem } from "@/lib/archive/checklists";
import type { ArchiveClosedReason } from "@prisma/client";

export interface LinkedDoc {
  id: string;
  name: string;
}

interface UseArchiveWizardProps {
  matterId: string;
}

export function useArchiveWizard({ matterId }: UseArchiveWizardProps) {
  const [loading, setLoading] = useState(true);
  const [checklist, setChecklist] = useState<ArchiveChecklist | null>(null);
  const [checked, setChecked] = useState<Record<string, boolean>>({});
  const [linkedDocs, setLinkedDocs] = useState<Record<string, LinkedDoc[]>>({});
  const [closedReason, setClosedReason] = useState<ArchiveClosedReason>("JUDGMENT" as ArchiveClosedReason);
  const [completedAt, setCompletedAt] = useState<string>(new Date().toISOString().slice(0, 10));
  const [summary, setSummary] = useState("");
  const [forceWithMissing, setForceWithMissing] = useState(false);
  const [isPending, startTransition] = useTransition();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const pendingItemRef = useRef<ArchiveChecklistItem | null>(null);
  const [uploadingItemId, setUploadingItemId] = useState<string | null>(null);

  async function refreshPrep() {
    const data = await getArchivePrepData(matterId);
    setChecklist(data.checklist);
    const autoChecked: Record<string, boolean> = {};
    for (const item of data.checklist.items) {
      if (item.autoGenerated) autoChecked[item.id] = true;
    }
    for (const itemId of Object.keys(data.docsByItem)) {
      autoChecked[itemId] = true;
    }
    setChecked(autoChecked);
    setLinkedDocs(data.docsByItem);
    if (data.matter.closedAt) {
      setCompletedAt(data.matter.closedAt.toISOString().slice(0, 10));
    }
    if (data.existingSummary) {
      setSummary(data.existingSummary);
    }
  }

  useEffect(() => {
    setLoading(true);
    refreshPrep()
      .catch((err) => {
        toast.error("加载归档数据失败", { description: err instanceof Error ? err.message : "" });
      })
      .finally(() => setLoading(false));
  }, [matterId]);

  const triggerUpload = useCallback((item: ArchiveChecklistItem) => {
    pendingItemRef.current = item;
    fileInputRef.current?.click();
  }, []);

  const handleFileSelected = useCallback(async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    e.target.value = "";
    const item = pendingItemRef.current;
    pendingItemRef.current = null;
    if (!file || !item) return;

    setUploadingItemId(item.id);
    try {
      const fd = new FormData();
      fd.set("matterId", matterId);
      fd.set("name", file.name.replace(/\.[^.]+$/, "") || item.label);
      fd.set("category", "OTHER"); // TODO: infer from item.id
      fd.set("archiveChecklistItemId", item.id);
      fd.set("encrypted", "false");
      fd.set("file", file);
      await uploadDocument(fd);
      toast.success(`已上传：${item.label}`, { description: file.name });
      await refreshPrep();
    } catch (err) {
      toast.error("上传失败", { description: err instanceof Error ? err.message : "" });
    } finally {
      setUploadingItemId(null);
    }
  }, [matterId]);

  const missingRequired = checklist
    ? checklist.items.filter((i) => !i.autoGenerated && i.required && !checked[i.id])
    : [];

  const handleSubmit = useCallback(async () => {
    if (!summary.trim()) {
      toast.warning("请填写结案小结");
      return;
    }
    if (missingRequired.length > 0 && !forceWithMissing) {
      toast.warning(`仍有 ${missingRequired.length} 项必交材料未勾选`, {
        description: "如确实无法补齐，请勾选下方的'强制归档（缺项记录在档）'"
      });
      return;
    }
    startTransition(async () => {
      try {
        const result = await archiveMatter({
          matterId,
          summary,
          closedReason,
          completedAt: new Date(completedAt),
          judgmentSummary: "",
          checklist: checked,
          forceWithMissing
        });
        toast.success(
          result.status === "APPROVED"
            ? `案件已归档（${result.archiveNo}）`
            : `归档申请已提交（${result.archiveNo}），等待管理员审批`,
          { description: "卷宗封皮 + 目录已自动生成至归档卷宗" }
        );
      } catch (err) {
        toast.error("归档失败", { description: err instanceof Error ? err.message : "" });
      }
    });
  }, [matterId, summary, closedReason, completedAt, checked, forceWithMissing, missingRequired.length]);

  return {
    loading,
    checklist,
    checked,
    linkedDocs,
    closedReason,
    completedAt,
    summary,
    setSummary,
    setClosedReason,
    setCompletedAt,
    forceWithMissing,
    setForceWithMissing,
    isPending,
    fileInputRef,
    uploadingItemId,
    triggerUpload,
    handleFileSelected,
    missingRequired,
    handleSubmit,
    refreshPrep
  };
}
