/*
 * Copyright 2026 叶森 (Sen Ye) - Original work (MIT Licensed)
 * Copyright 2026 COTAPELU - Modifications and additions (Apache 2.0 Licensed)
 *
 * This file contains modifications to the original MIT-licensed work.
 *
 * The original work was licensed under MIT License (see below):
 * Copyright (c) 2026 叶森 (Sen Ye)
 *
 * Modifications in this file are licensed under the Apache License, Version 2.0.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * ORIGINAL MIT LICENSE TEXT:
 * ==========================
 * MIT License
 *
 * Copyright (c) 2026 叶森 (Sen Ye)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
/**
 * v0.9.4 归档必交材料 checklist
 *
 * 三套清单按 Matter.category 映射：
 *   - 诉讼类（民商/刑事/行政）→ LITIGATION
 *   - 非诉 / 专项 → NON_LITIGATION
 *   - 顾问 → LEGAL_COUNSEL
 *
 * required=true 的项缺失会在归档确认页报警告（不阻断，律师可强制归档但需记入 missingItems）。
 * autoGenerated=true 的项由系统在归档时自动生成（封皮 / 目录），律师无须手动勾选。
 */
import type { MatterCategory } from "@prisma/client";

export type ArchiveChecklistKind = "LITIGATION" | "NON_LITIGATION" | "LEGAL_COUNSEL";

export interface ArchiveChecklistItem {
  id: string;
  label: string;
  required: boolean;
  autoGenerated?: boolean;
  hint?: string;
}

export interface ArchiveChecklist {
  kind: ArchiveChecklistKind;
  title: string;
  items: ArchiveChecklistItem[];
}

const LITIGATION: ArchiveChecklist = {
  kind: "LITIGATION",
  title: "诉讼案件归档清单",
  items: [
    { id: "retainer_contract", label: "委托代理合同", required: true },
    { id: "power_of_attorney", label: "授权委托书", required: true },
    { id: "risk_disclosure", label: "风险告知书", required: false },
    { id: "intake_form", label: "收案登记表", required: false },
    { id: "pleading", label: "起诉状 / 答辩状 / 上诉状", required: true, hint: "按本方立场提交一份即可" },
    { id: "evidence_catalog", label: "证据目录及证据材料", required: true },
    { id: "hearing_record", label: "庭审 / 谈话 / 阅卷笔录", required: false },
    { id: "agent_opinion", label: "代理词 / 律师函", required: false },
    { id: "judgment", label: "裁判文书（判决书 / 裁定书 / 调解书）", required: true },
    { id: "closing_form", label: "结案登记表", required: true },
    { id: "case_summary", label: "办案小结", required: true },
    { id: "fee_receipt", label: "收费凭证", required: false },
    { id: "archive_cover", label: "卷宗封皮", required: true, autoGenerated: true },
    { id: "archive_catalog", label: "卷宗目录", required: true, autoGenerated: true }
  ]
};

const NON_LITIGATION: ArchiveChecklist = {
  kind: "NON_LITIGATION",
  title: "非诉 / 专项归档清单",
  items: [
    { id: "retainer_contract", label: "委托代理合同", required: true },
    { id: "intake_form", label: "收案登记表", required: false },
    { id: "legal_opinion", label: "调研报告 / 法律意见书", required: true },
    { id: "working_papers", label: "工作底稿", required: false },
    { id: "issued_documents", label: "出具的法律文件（合同审查意见 / 律师见证 / 尽调报告等）", required: true },
    { id: "client_confirmation", label: "客户确认函 / 验收材料", required: false },
    { id: "closing_form", label: "结案登记表", required: true },
    { id: "case_summary", label: "办案小结", required: true },
    { id: "fee_receipt", label: "收费凭证", required: false },
    { id: "archive_cover", label: "卷宗封皮", required: true, autoGenerated: true },
    { id: "archive_catalog", label: "卷宗目录", required: true, autoGenerated: true }
  ]
};

const LEGAL_COUNSEL: ArchiveChecklist = {
  kind: "LEGAL_COUNSEL",
  title: "法律顾问归档清单",
  items: [
    { id: "counsel_contract", label: "法律顾问合同", required: true },
    { id: "consultation_log", label: "咨询记录汇总", required: false },
    { id: "legal_opinions_compendium", label: "出具的法律意见 / 律师函汇总", required: true },
    { id: "contract_reviews", label: "合同审查意见汇总", required: false },
    { id: "training_records", label: "培训记录", required: false },
    { id: "fee_receipt", label: "收费凭证", required: false },
    { id: "term_summary", label: "期满总结 / 续约 / 终止说明", required: true },
    { id: "archive_cover", label: "卷宗封皮", required: true, autoGenerated: true },
    { id: "archive_catalog", label: "卷宗目录", required: true, autoGenerated: true }
  ]
};

const CHECKLISTS: Record<ArchiveChecklistKind, ArchiveChecklist> = {
  LITIGATION,
  NON_LITIGATION,
  LEGAL_COUNSEL
};

export function checklistForCategory(category: MatterCategory): ArchiveChecklist {
  switch (category) {
    case "CIVIL_COMMERCIAL":
    case "CRIMINAL":
    case "ADMINISTRATIVE":
      return LITIGATION;
    case "NON_LITIGATION":
    case "SPECIAL_PROJECT":
      return NON_LITIGATION;
    case "LEGAL_COUNSEL":
      return LEGAL_COUNSEL;
    default:
      return LITIGATION;
  }
}

export function getChecklist(kind: ArchiveChecklistKind): ArchiveChecklist {
  return CHECKLISTS[kind];
}

/**
 * 评估勾选状态：返回缺项 + 是否阻断警告
 */
export function evaluateChecklist(
  checklist: ArchiveChecklist,
  checked: Record<string, boolean>
): { missingRequired: ArchiveChecklistItem[]; missingOptional: ArchiveChecklistItem[] } {
  const missingRequired: ArchiveChecklistItem[] = [];
  const missingOptional: ArchiveChecklistItem[] = [];
  for (const item of checklist.items) {
    if (item.autoGenerated) continue;
    if (checked[item.id]) continue;
    if (item.required) missingRequired.push(item);
    else missingOptional.push(item);
  }
  return { missingRequired, missingOptional };
}
