/*
 * Copyright 2026 叶森 (Sen Ye) - Original work
 * Copyright 2026 COTAPELU - Modifications and additions
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file is part of a derivative work based on the original MIT-licensed project.
 * Original author: 叶森 (Sen Ye) - Copyright 2026
 */
/**
 * v0.9.4 Checklist vật lý cần nộp khi lưu trữ vụ án
 *
 * Ba bộ checklist ánh xạ theo Matter.category:
 *   - Tố tụng (dân sự/hình sự/hành chính) → LITIGATION
 *   - Phi tố tụng / Đề án đặc biệt → NON_LITIGATION
 *   - Tư vấn → LEGAL_COUNSEL
 *
 * required=true: thiếu sẽ báo động (không chặn, luật sư có thể ép lưu trữ nhưng ghi nhận missingItems).
 * autoGenerated=true: hệ thống tự tạo (bìa / mục lục), luật sư không cần chọn.
 */
import type { MatterCategory } from "@prisma/client";

export type ArchiveChecklistKind = "LITIGATION" | "NON_LITIGATION" | "LEGAL_COUNSEL";

export interface ArchiveChecklistItem {
  id: string;
  label: string;
  required: boolean;
  autoGenerated?: boolean;
  hint?: string;
}

export interface ArchiveChecklist {
  kind: ArchiveChecklistKind;
  title: string;
  items: ArchiveChecklistItem[];
}

const LITIGATION: ArchiveChecklist = {
  kind: "LITIGATION",
  title: "Danh sách lưu trữ vụ án tố tụng",
  items: [
    { id: "retainer_contract", label: "Hợp đồng ủy quyền", required: true },
    { id: "power_of_attorney", label: "Giấy ủy quyền", required: true },
    { id: "risk_disclosure", label: "Công bố rủi ro", required: false },
    { id: "intake_form", label: "Biểu mẫu đăng ký nhận vụ án", required: false },
    { id: "pleading", label: "Trang trình tố / Biện luận / Khiếu nại", required: true, hint: "Chỉ cần nộp một theo vị trí của mình" },
    { id: "evidence_catalog", label: "Mục lục chứng cứ và tài liệu", required: true },
    { id: "hearing_record", label: "Biên bản phiên tòa / Trao đổi / Xem hồ sơ", required: false },
    { id: "agent_opinion", label: "Nhận xét của luật sư / Thư luật sư", required: false },
    { id: "judgment", label: "Văn bản tòa án (Phán quyết / Quyết định / Thỏa thuận)", required: true },
    { id: "closing_form", label: "Biểu mẫu kết thúc vụ án", required: true },
    { id: "case_summary", label: "Tóm tắt xử lý vụ án", required: true },
    { id: "fee_receipt", label: "Biên lai phí dịch vụ", required: false },
    { id: "archive_cover", label: "Bìa hồ sơ lưu trữ", required: true, autoGenerated: true },
    { id: "archive_catalog", label: "Mục lục hồ sơ lưu trữ", required: true, autoGenerated: true }
  ]
};

const NON_LITIGATION: ArchiveChecklist = {
  kind: "NON_LITIGATION",
  title: "Danh sách lưu trữ phi tố tụng / Đề án đặc biệt",
  items: [
    { id: "retainer_contract", label: "Hợp đồng ủy quyền", required: true },
    { id: "intake_form", label: "Biểu mẫu đăng ký nhận vụ án", required: false },
    { id: "legal_opinion", label: "Báo cáo nghiên cứu / Ý kiến pháp lý", required: true },
    { id: "working_papers", label: "Giấy tờ làm việc", required: false },
    { id: "issued_documents", label: "Văn bản pháp lý đã phát hành (Ý kiến hợp đồng / Chứng thực / Báo cáo due diligence...)", required: true },
    { id: "client_confirmation", label: "Thư xác nhận / Chứng từ nghiệm thu", required: false },
    { id: "closing_form", label: "Biểu mẫu kết thúc vụ án", required: true },
    { id: "case_summary", label: "Tóm tắt xử lý vụ án", required: true },
    { id: "fee_receipt", label: "Biên lai phí dịch vụ", required: false },
    { id: "archive_cover", label: "Bìa hồ sơ lưu trữ", required: true, autoGenerated: true },
    { id: "archive_catalog", label: "Mục lục hồ sơ lưu trữ", required: true, autoGenerated: true }
  ]
};

const LEGAL_COUNSEL: ArchiveChecklist = {
  kind: "LEGAL_COUNSEL",
  title: "Danh sách lưu trữ luật sư tư vấn",
  items: [
    { id: "counsel_contract", label: "Hợp đồng tư vấn", required: true },
    { id: "consultation_log", label: "Tổng hợp nhật ký tư vấn", required: false },
    { id: "legal_opinions_compendium", label: "Tổng hợp ý kiến pháp lý / Thư luật sư", required: true },
    { id: "contract_reviews", label: "Tổng hợp ý kiến xem xét hợp đồng", required: false },
    { id: "training_records", label: "Hồ sơ đào tạo", required: false },
    { id: "fee_receipt", label: "Biên lai phí dịch vụ", required: false },
    { id: "term_summary", label: "Tóm tắt hết hạn / Gia hạn / Giải thích chấm dứt", required: true },
    { id: "archive_cover", label: "Bìa hồ sơ lưu trữ", required: true, autoGenerated: true },
    { id: "archive_catalog", label: "Mục lục hồ sơ lưu trữ", required: true, autoGenerated: true }
  ]
};

const CHECKLISTS: Record<ArchiveChecklistKind, ArchiveChecklist> = {
  LITIGATION,
  NON_LITIGATION,
  LEGAL_COUNSEL
};

export function checklistForCategory(category: MatterCategory): ArchiveChecklist {
  switch (category) {
    case "CIVIL_COMMERCIAL":
    case "CRIMINAL":
    case "ADMINISTRATIVE":
      return LITIGATION;
    case "NON_LITIGATION":
    case "SPECIAL_PROJECT":
      return NON_LITIGATION;
    case "LEGAL_COUNSEL":
      return LEGAL_COUNSEL;
    default:
      return LITIGATION;
  }
}

export function getChecklist(kind: ArchiveChecklistKind): ArchiveChecklist {
  return CHECKLISTS[kind];
}

/**
 * 评估勾选状态：返回缺项 + 是否阻断警告
 */
export function evaluateChecklist(
  checklist: ArchiveChecklist,
  checked: Record<string, boolean>
): { missingRequired: ArchiveChecklistItem[]; missingOptional: ArchiveChecklistItem[] } {
  const missingRequired: ArchiveChecklistItem[] = [];
  const missingOptional: ArchiveChecklistItem[] = [];
  for (const item of checklist.items) {
    if (item.autoGenerated) continue;
    if (checked[item.id]) continue;
    if (item.required) missingRequired.push(item);
    else missingOptional.push(item);
  }
  return { missingRequired, missingOptional };
}
